
CREATE VIEW PUVIEWEXCISECOLLECT AS
SELECT               MAX(TIME) AS DATE,
                     MAX(TRANSACTIONNUMBER) AS TRANSACTIONNUMBER, 
                     MAX(TIME) AS SHIPDATE, 
                     MAX(ACCOUNTNUMBER) AS ACCOUNTNUMBER,
                     MAX(COMPANY) AS COMPANY,     
                     MAX(CAST(TAXEXEMPT AS TINYINT)) AS TAXEXEMPT,
                     MAX(TAXNUMBER) AS TAXNUMBER,
                     MAX(CUSTOMTEXT2) AS TLIC, 
                     CASE WHEN PUESUBDESCRIPTION3 = 'LT10COLL' THEN SUM(PUECOST * PUEQUANTITY)  ELSE 0 END AS LOOSETOBACCO,
                     CASE WHEN PUESUBDESCRIPTION3 = 'SL10COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS SMOKELESS,
                     CASE WHEN PUESUBDESCRIPTION3 = 'LC23COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS LARGECIGARS,
                     CASE WHEN PUESUBDESCRIPTION3 = 'LC25COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS LITTLECIGARS, 
                     CASE WHEN PUESUBDESCRIPTION3 = 'VO07COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS VAPORSOPEN, 
	             CASE WHEN PUESUBDESCRIPTION3 = 'VD07COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS VAPORSDEVICE,
                     CASE WHEN PUESUBDESCRIPTION3 = 'VC05COLL' THEN SUM(PUECOST * PUEQUANTITY) ELSE 0 END AS VAPORSCLOSED,
                     CASE WHEN PUESUBDESCRIPTION3 = 'LC25COLL' THEN SUM(PUEQUANTITY * IWEIGHT) ELSE 0 END AS LITTLECIGARSWEIGHT,
                     CASE WHEN PUESUBDESCRIPTION3 = 'VC05COLL' THEN SUM(PUEQUANTITY * IWEIGHT) ELSE 0 END AS VAPORSCLOSEDWEIGHT,

		     SUM(PUEPRICEC * PUEQUANTITY) AS TOTALEXCISECOLLECT,
                     SUM(PUEPRICE * PUEQUANTITY) AS TOTALSALES
FROM         DBO.PUVIEWEXCISETRANSACTION
GROUP BY TRANSACTIONNUMBER, PUESUBDESCRIPTION3

